#!/usr/bin/env bash

# Build project for production

[[ $(id -u) != 0 ]] && echo "Error: Must be run as sudo/root." && exit 1

manage() {
	cd /var/www/bita.sh
	venv/bin/python server/manage.py $@ --settings=config.settings_production
	cd - >/dev/null
}

manage migrate
manage collectstatic --noinput

if command -v getenforce >/dev/null && [[ $(getenforce) = Enforcing ]]; then
	# Restore SELinux context of files (default file label should be httpd_sys_content_t)
	echo "Relabel venv/lib/python3.8/site-packages and all its contents from unconfined_u:object_r:var_t:s0 to unconfined_u:object_r:httpd_sys_content_t:s0"
	/sbin/restorecon -R venv/lib/python3.8/site-packages
	echo "Relabel server/* from unconfined_u:object_r:var_t:s0 to unconfined_u:object_r:httpd_sys_content_t:s0"
	/sbin/restorecon -R server
	echo "Relabel static/* from unconfined_u:object_r:var_t:s0 to unconfined_u:object_r:httpd_sys_content_t:s0"
	/sbin/restorecon -R static
	echo "Relabel uploads/* from unconfined_u:object_r:var_t:s0 to unconfined_u:object_r:httpd_sys_content_t:s0"
	/sbin/restorecon -R uploads
	/sbin/restorecon -v secret_key.txt
	/sbin/restorecon -v venv/pyvenv.cfg
	/sbin/restorecon -v venv/bin/gunicorn
	/sbin/restorecon -v nginx.conf
fi

