#!/usr/bin/env bash

# Run django-admin manage command using production settings
[[ $# = 0 ]] && echo "Error: Argument required." && exit 1

cd /var/www/bita.sh
venv/bin/python server/manage.py $@ --settings=config.settings_production

